### ISSUE TITLE
Admin - User Mamagment

### ISSUE THREAD

**Issue by merzido** [MerDoLive/AdminPanel#1]

**Comment by merzido** [comment]
Picked up the item now

**Comment by rushikeshnakhate** [comment]
Need to design table Structure for Admin - User Mamagment

**Comment by akashkulkarni01** [comment]
there is an error showing "This page isn't working
 ec2-54-255-229-68.ap-southeast-1.compute.amazonaws.com is currently unable to handle this request.
HTTP ERROR 500"

**Comment by akashkulkarni01** [comment]
solved the "This page isn't working" error. it happened because users.php in the controller wasn't able to access user_model properly

**Comment by akashkulkarni01** [comment]
Errors in the add user form and update user details. Update user page unable to load

**Comment by akashkulkarni01** [comment]
issues in the retrieval of user type id from the user_role_mstr table when adding a new user to the user_mstr table from user management.

**Comment by akashkulkarni01** [comment]
delete function is not working because id is not accepting in the URL

**Comment by merzido** [comment]
- User to have change password Option

**Comment by merzido** [comment]
Bug - When clicked on Edit the Role mapped to User to be displayed
![bug](https://user-images.githubusercontent.com/40512484/44954884-53fe1a00-aedc-11e8-9f95-e2535d11630d.png)
 , Its showing Empty now .

**Comment by kailash05** [comment]
![screenshot 2](https://user-images.githubusercontent.com/42354813/45075262-30b5b380-b104-11e8-9dc8-cc0a632c4ecd.png)
![screenshot 3](https://user-images.githubusercontent.com/42354813/45075319-60fd5200-b104-11e8-8ec7-cce6eb3e5ab7.png)

**Comment by kailash05** [comment]
Hello sir ,
change password option is updated..

**Comment by merzido** [comment]
@Abhijitshahakar - Please check for the issue
