### ISSUE TITLE
User Terminal - Layout Details

### ISSUE THREAD

**Issue by merzido** [MerDoLive/AdminPanel#26]

**Comment by merzido** [comment]
- Search Product /Category Should Work .
- Please verify layout for Deals and priority Category .

**Comment by merzido** [comment]
User Terminal - user Login

**Comment by merzido** [comment]
ETA 2 Days

**Comment by kailash05** [comment]
1.in sellhub when we click on logo it redirect to to the login page .
so i fix that issue .using '#' insted of base url 
(/var/www/html/dev/sellerhub/application/views/seller/include/header=39)

2.remove hard coded path for favicon =28

3.i remove all hard coded path from include folder.(header.php and footer.php)
  

/var/www/html/dev/sellerhub/application/views/product

1.mange.php -> no hard codedpath in this code
2.view.php-> no hard codepth in this code
3.upload_image.php->no hard codepth in this code
4.update_uploaded_img.php-
5.sku_image.php->
6.search_result.php->
7.product_info.php_Before_brnd_change->
8.product_info.php->
9.more_info.php->
10.manageImage.php->
11.import.php->
12.images.php->
13.create.php->


#/var/www/html/dev/sellerhub/application/views/seller
1.viewPromotion.php->
2.template.php->
3.restricted.php->
4.reg_success.php->
5.promotions.php->
6.profile.php->
7.myPromotions.php->
8.login->remove hard coded path


#/var/www/html/dev/sellerhub/application/views/deals



checked all the files in this folder ..(no hard coded path is their) 

#/var/www/html/dev/sellerhub/application/models

checked all the files in this folder ..(no hard coded path is their) 


#/var/www/html/dev/sellerhub/application/logs
checked all the files in this folder ..(no hard coded path is their)



#var/www/html/dev/sellerhub/application/controllers



checked all the files in this folder ..(no hard coded path is their)



also work on CodeIgniter PHP framework and study about the how to call the  project index page .
