### ISSUE TITLE
Admin - Product Management  - old task - closing it for now 

### ISSUE THREAD

**Issue by merzido** [MerDoLive/AdminPanel#8]

**Comment by merzido** [comment]
- When clicked on Product Management all product to be displayed. 
- Page to have edit , delete , view , Add button , copy selected .
- Page have checkbox for bulk action .
- Admin to edit all attributes of Product except ID
- Page to have multiple level of filter , ( Seller Name , Category  , Status ( all possible status ) 
- ADD - admin can add product one by one or in Bulk .
**-  One By One** 
   - Choose Category 
   - All the attributes mapped to category Admin has to provide . 
   - Each filed for product attributes to be validated against datatype ( Exa: Name cannot be number ) 
    - By default Product created by Admin would have status 'PNDG' , needs approval.

**- Bulk ** 
   -   User Can Upload the product in csv or xls format .
   -  TBD

**Comment by merzido** [comment]
1.when clicked on Edit getting below  PHP Error 

Severity: Notice

Message: Undefined property: stdClass::$PRODUCT_MSTR_BRAND_NAME

Filename: controllers/Products.php

Line Number: 310

Backtrace:

File: /var/www/html/dev/NewJoinTest/application/controllers/Products.php
Line: 310
Function: _error_handler

File: /var/www/html/dev/NewJoinTest/index.php
Line: 292
Function: require_once

--
A PHP Error was encountered
Severity: Notice

Message: Undefined property: stdClass::$PRODUCT_MSTR_BRAND_DESC

Filename: controllers/Products.php

Line Number: 311

Backtrace:

File: /var/www/html/dev/NewJoinTest/application/controllers/Products.php
Line: 311
Function: _error_handler

File: /var/www/html/dev/NewJoinTest/index.php
Line: 292
Function: require_once


An Error Was Encountered
Unable to load the requested file: Products/form.php



==============================================

2. When clicked on ADD Product ->select catg-> brand->Submit 
Please remove **Description** text 

3.Can you please try to change the design of dropDown this Looks Bit simple

4.while inserint Data into PRODUCT_ATTR_MAP Can you please also inset values for PRODUCT_ATTR_MAP_CATEGORY_NAME and PRODUCT_ATTR_MAP_ATTR_NAME .


Overall good!! We need to improve design bit when showing attributes using some effective features from Bootstrap.

**Comment by roshani1991** [comment]
ok

**Comment by roshani1991** [comment]
Above changes performed

**Comment by merzido** [comment]
Hi Roshni  , When I tried add product under 
Category: LAPTOPS ULTRA BOOKS I can see some attributes are shown as below , Please can you check product management complete flow once .
I have added multiple attributes to Database ,
Please map attributes of all type to category ( int  , string , char) , and also with textbox , dropdown and all other values and try to create product under such category. 

![untitled](https://user-images.githubusercontent.com/40512484/44007593-1e2c8946-9ecb-11e8-9d4a-fb496850a70f.png)


Please check at the end .

**Comment by merzido** [comment]
HI Roshini  , Please also do the changes to add images for product , Please refer to upload image section for more details.

**Comment by roshani1991** [comment]
Those attribute display type is missing in the database,
But no issue i added some condition so afterword if attribute display type is Not available it will not show such attribute.

**Comment by merzido** [comment]
HI Kamlesh , 

Product managment - 

Please work with Roshni and try to test Product managment
1. Create atttributes 
2. atttributes can ne string ,int , char 
3. atttributes can be show with 8 possible type  ( checkBox , html editor , textbox ....) 
4. Product can have multiple iamges 
5. Please try to create prudct and confirm that u are able to see attributes  correclty when we add the product from add product

**Comment by roshani1991** [comment]
I added option to upload image from first page where we can edit,delete and view product with their attributes.

**Comment by kailash05** [comment]
![screenshot 5](https://user-images.githubusercontent.com/42354813/44079386-80c54a56-9fc6-11e8-84b0-1c5e732d431d.png)


in product mangment -> uploade image ->group*->fist i select the product and then select  Select Image Group
and then error is occur

**Comment by roshani1991** [comment]
Image upload issue resolved.
as well as edit image option added in edit product panel.

**Comment by kailash05** [comment]
product mangement-> uplode image ->start date and end date .
in end date user can enter the back date value

![date problem](https://user-images.githubusercontent.com/42354813/44192426-fed8af00-a14c-11e8-8fd4-e820faded336.png)

**Comment by kailash05** [comment]
Product Mangment ->uplode image -> group*(select option`= select image group )-> submit
 when user click on submit button error is occured
![group img](https://user-images.githubusercontent.com/42354813/44192462-1f086e00-a14d-11e8-837c-3f8f9c5ca24b.png)

**Comment by kailash05** [comment]
Attribute mangment  -> add -> user enter the name with special char is allow .but
in other side when user want to change the same name with special char .in "EDIT" option
user get validation massage "please enter valid name" 
  so please check it.

**Comment by kailash05** [comment]
Attribute mangment  -> add ->Attribute Type when user select type = int,
  -> value(in this option  only  "int" type is allow.  when user select the Attribute Type= int ).
   but now user can  ADD any value in  (value* option )
![int](https://user-images.githubusercontent.com/42354813/44196671-2f731580-a15a-11e8-8171-682186e9dca7.png)

**Comment by kailash05** [comment]
same error occur with   "char" value and "STRING"     
When  user select the attribute type =CHAR or STRING
   and then user go to the  value option 
user enter any value, in value box ..
so please fix the code with correct validition  

like if user select the  attribute type = char
then  in value  = only char value

**Comment by merzido** [comment]
@ Rushikesh- Please confirm the Column for ATTR_MSTR to identify its going to be fixed .

**Comment by merzido** [comment]
@Abhijit , Rushikesh Mydeen - How to manage the product  with multiple color
